checkpoints_dir: ./checkpoints
results_dir: ./results
data_dir: ./data
logs_dir: ./logs

# Prints the parsed config
print_args: True

# Throws error after print_args
dry_run: False

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .
