defaults:
  - global@_global_: default
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 942

year: 2017
model_name: "meta-llama/Meta-Llama-3-8B-Instruct"
#model_name: "hf-internal-testing/tiny-random-LlamaForCausalLM"

data:
  max_length: 512
  num_offset_tokens: 1

batch_size: 32

model:
  set_pad_token: true
  compile: false
  better_transformer: true

acceleration:
  device_map: auto
  torch_dtype: "fp16"
  bits_and_bytes: false
  low_cpu_mem_usage: true
  data_device: "cuda:0"
  max_gpu_memory: "40GB"
  max_cpu_memory: "120GB"
