#!/bin/bash

#SBATCH --job-name=misinfo
#SBATCH --time=06:00:00

# GPU Settings
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --partition=gpu
#SBATCH --array=2-6

#SBATCH --output=./job_outputs/misinfo_benchmark_models/uniform-eval/%A-%a.out

set -e

# Move data to scratch system for fast loading
# Probably not needed for this project
mkdir -p /scratch-local/ivov/misinfo_benchmark_models/data/
LOCAL_DATA_DIR=/scratch-local/ivov/misinfo_benchmark_models/data/
rm -rf LOCAL_DATA_DIR/*
echo -e "Syncing data to node"
rsync -aru $HOME/misinfo_benchmark_models/data/* $LOCAL_DATA_DIR
echo -e "Finished syncing data to node"

# Load environment
module purge
module load 2023
module load Anaconda3/2023.07-2

# Make sure we're in the right directory
cd $HOME/misinfo_benchmark_models/

# Activate environment
source activate misinfo_benchmark

HPARAMS=$HOME/misinfo_benchmark_models/scripts/arrays/year_fold_eval-year_array.txt

srun python src/test_uniform.py \
    seed=942 \
    ++split.split_name='val' \
    checkpoint.model_name="microsoft/deberta-v3-base"\
    disable_progress_bar=true \
    $(head -$SLURM_ARRAY_TASK_ID $HPARAMS | tail -1)

rsync -aru $LOCAL_DATA_DIR/processed/* $HOME/misinfo_benchmark_models/data/processed
